#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")" && pwd)"
STORE_H="$ROOT/WolFoxProStore.h"
STORE_M="$ROOT/WolFoxProStore.m"
MANAGER="$ROOT/WFSpoofScheduleManager.m"
UI="$ROOT/WolFoxMaster.mm"
BUILD="$ROOT/build_v1_deb.sh"

grep -q 'scheduleLocationID' "$STORE_H"
grep -q 'WF_PRO_SCHEDULE_DAYS' "$STORE_M"
grep -q 'UIApplicationDidBecomeActiveNotification' "$MANAGER"
grep -q 'WFLicenseClient isRuntimeLicenseValid' "$MANAGER"
grep -q 'scheduledLocation' "$MANAGER"
grep -q 'autoupdatingCurrentCalendar' "$MANAGER"
grep -q '_timer.tolerance = 5.0' "$MANAGER"
grep -q -- '- (void)dealloc' "$MANAGER"
grep -q 'WF_SCHEDULE_LOCATION_DELETED' "$MANAGER"
grep -q 'WF_SCHEDULE_LOCATION_MISSING' "$MANAGER"
grep -q 'WF_SCHEDULE_LOCATION_DELETED' "$STORE_M"
grep -q 'committedScheduleEnabled' "$STORE_H"
grep -q 'commitScheduleDraft' "$STORE_M"
grep -q 'hasCommittedSchedule' "$MANAGER"
grep -q 'updateTimerState' "$MANAGER"
grep -q 'showSpoofSchedulePage' "$UI"
grep -q 'calendar.badge.clock' "$UI"
grep -q 'minuteInterval = 1' "$UI"
grep -q 'closeScheduleTimePicker' "$UI"
grep -q 'confirmScheduleTimePicker' "$UI"
grep -q 'autoupdatingCurrentCalendar' "$UI"
grep -q 'scheduleApplied = NO' "$UI"
grep -q 'scheduleStateChanged:' "$UI"
grep -q 'scheduleLocationMissing:' "$UI"
grep -q 'showScheduleLocationMissingNotice' "$UI"
grep -q 'scheduleEnabled = sender.on;' "$UI"
grep -q 'saveSettings' "$UI"
grep -q 'scheduleDraftDirty = YES' "$UI"
grep -q 'commitScheduleDraft' "$UI"
grep -q 'updateTimerState' "$UI"
grep -q 'WFSpoofScheduleManager.m' "$BUILD"

echo "Schedule static test: passed"
